### PR TITLE
pull request for ocean 1 (plus preview concerns)

### PR DESCRIPTION
**Pull request by safesocks**
issue with gatsby not being recognized when attempting to run npm run develop, so was unable to preview article. suspect issue is that it did not seem to register that i was asking it to do that with the index file (my 'location' was marked as workspaces/simplysynbio in the terminal)? would be great if it could be double checked by someone who can make it work prior to publish. thanks!

### CODE REVIEW

**Comment by lhao03** [comment]
I'll check this out! You might have needed to run `npm install` if gatsby wasn't being recognised.

**Comment by lhao03** [comment]
Peek 2024-02-19 09-26

**Comment by lhao03** [comment]
This looks good from my end if you want to merge @yejonlhee!

**Comment by yejonlhee** [comment]
awesome thanks! will push now!

**Pull request merged**
